// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250531150718_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Data.Entities.RestrictionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restrictions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Weapons and Dangerous Items",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-1.svg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Illegal Substances",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-2.svg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Alcohol and Beverages",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-3.svg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Recording Equipment",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-4.svg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Large or Hazardous Items",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-5.svg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Noise Makers and Disruptive Items",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-6.svg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Unauthorized Merchandise",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-7.svg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pets and Animals",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-8.svg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Bicycles, Skateboards, or Hoverboards",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-9.svg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Coolers or Picnic Baskets",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-10.svg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Umbrellas or Large Parasols",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-11.svg"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Camping Gear",
                            ImageUrl = "https://ventixedatastorage.blob.core.windows.net/images/prohibited-item-12.svg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
